spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/root
    platform: mysql
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
