spring:
  profiles.active: @spring.profile@
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        ejb.interceptor: com.ohtacaesar.misc.spring_boot_sandbox.HibernateInterceptor
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
