version: '3.7'
services:
  serverless:
    build:
      context: ./
    volumes:
      - ./app:/root/app
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'

